### PR TITLE
Upmerge and add ability to mock Zookeeper functions

### PR DESCRIPTION
**Pull request by revans2**
The test still don't compile, but the one test complaining about mkdirs does.

Most of this is an upmerge only the very last commit is the one that adds the mocking.  Do you want me to look at making the rest of the tests compile?

### CODE REVIEW

**Comment by revans2** [comment]
Wait I'll try and address https://github.com/apache/storm/pull/1047/files#r50996403 too.

**Comment by revans2** [comment]
I now have all of the tests compiling, but like I said before there are still some errors in the code that are making the tests not pass, and in some cases exit early.

I have found when doing things like this it is fastest to migrate one function at a time and run the tests in-between each migration to catch the bugs early on.  If you do want help in fixing the tests please let me know.

**Comment by revans2** [comment]
OK I fixed the rest of the errors and everything seems to be running OK.

**Comment by hustfxj** [comment]
@revans2  thank you very much

**Pull request merged**
